### ISSUE TITLE
[Bug]前端展示效果建议修复

### ISSUE THREAD

**Issue by snpyeso** [kubecube-io/KubeCube#109]
![图片](https://user-images.githubusercontent.com/15830225/167336322-ce8086dd-8b52-4019-8109-e89a8a1a63ef.png)

可以看看下拉组件展示效果，很难去判断选中状态，显示也很不理想，也许是因为只有一条的原因

**Comment by zhujf1989** [comment]
//cc @sjm1202

**Comment by sjm1202** [comment]
请问用的是哪个浏览器

**Comment by sjm1202** [comment]
建议使用Chrome浏览器

**Comment by snpyeso** [comment]
> 建议使用Chrome浏览器
嗯，使用chrome显示正常
