### ISSUE TITLE
[Feature]建议新增master节点是否安装kube被调度的相关组件

### ISSUE THREAD

**Issue by snpyeso** [kubecube-io/KubeCube#110]
###生产环境大部分时候
* 不会安装master被调度的组件，只会是master可以调度其他，所以就是在安装的时候就可以排除不需要的

**Comment by zhujf1989** [comment]
这个描述不是很理解，是不想新增加的master node上部署master组件？使用污点或者直接以worker角色加入是否可以？

**Comment by snpyeso** [comment]
> 
你这么说好像也可以，我的意思是很多安装生产环境的时候master上不会装kubelet
