### ISSUE TITLE
[Feature]能否增加离线安装包

### ISSUE THREAD

**Issue by snpyeso** [kubecube-io/KubeCube#111]
* 太多情况下会是内网环境，或者有一台可以上网，其他服务起运行安装脚本太程序有点繁琐和复杂

**Comment by zhujf1989** [comment]
感谢反馈，计划下个版本支持离线部署。
//cc @tiancandevloper

**Comment by snpyeso** [comment]
> 好的，持续关注，感觉刚好很合适我的当前业务，
