### ISSUE TITLE
[Bug] I installed all in one,bug there's some problerm with me 

### ISSUE THREAD

**Issue by snpyeso** [kubecube-io/KubeCube#114]
![image](https://user-images.githubusercontent.com/15830225/169656986-e952fa70-dc58-4942-b178-30584378d868.png)

Internal error occurred: failed calling webhook "vresourcequota.kb.io": failed to call webhook: Post "https://warden.kubecube-system.svc:8443/validate-core-kubernetes-v1-resource-quota?timeout=10s": service "warden" not found

**Comment by weilaaa** [comment]
Please check out if there is service warden in specified ns by `kubectl get svc -n kubecube-system`, once not found, we should check out kubecube logs, search keywords `warden`.

**Comment by snpyeso** [comment]
> 

thanks,it's resolved

**Comment by snpyeso** [comment]
> Please check out if there is service warden in specified ns by `kubectl get svc -n kubecube-system`, once not found, we should check out kubecube logs, search keywords `warden`.

thanks,it's resolved
