### ISSUE TITLE
[Bug]日志输出乱码

### ISSUE THREAD

**Issue by snpyeso** [kubecube-io/KubeCube#138]
日志输出乱码
![image](https://user-images.githubusercontent.com/15830225/177491927-628773e6-6920-430a-ba2f-b172eb2757c6.png)

使用portainer 输出一切正常
![image](https://user-images.githubusercontent.com/15830225/177492965-1b7252ef-42a4-4fbb-a5b1-f15cb7ea7fae.png)

spring boot 项目
logback-输出日志

**Comment by ethfoo** [comment]
这个是日志里带了高亮展示导致的，如果你用文本编辑器打开日志文件也会看到有类似的一些符号。
有很多terminal会自动识别，kubecube前端可以尝试适配一下。

**Comment by snpyeso** [comment]
> 这个是日志里带了高亮展示导致的，如果你用文本编辑器打开日志文件也会看到有类似的一些符号。 有很多terminal会自动识别，kubecube前端可以尝试适配一下。
是测试了去除高亮一切OK
