### ISSUE TITLE
[Bug]节点添加脚本错误相关问题

### ISSUE THREAD

**Issue by daixh302** [kubecube-io/KubeCube#22]
**问题一：向集群添加工作节点时执行脚本install.sh报错**
`2021-08-18 15:45:41 INFO get docker binary from local
/bin/mv: cannot stat ‘/etc/kubecube/packages/docker-ce/linux/static/stable/x86_64/docker-19.03.8.tgz’: No such file or directory
2021-08-18 15:45:41 ERROR install kubernetes failed`

真正packages目录是在packages-master中：
`[root@test-ec2 x86_64]# pwd
/etc/kubecube/packages-master/docker-ce/linux/static/stable/x86_64
[root@gtlm-ec2 x86_64]# ls
docker-19.03.8.tgz`

**问题二：添加新节点时，给的步骤链接404**
链接：https://www.kubecube.io/docs/部署指南/添加节点/#向集群添加工作节点

**问题三：**
创建新集群时，过程与文档：https://www.kubecube.io/docs/installation-guide/add-member-k8s 完全不符！
这个问题新手遇到容易发狂！

**Comment by zhujf1989** [comment]
//cc @weilaaa

**Comment by zhujf1989** [comment]
@daixh302 感谢反馈！能具体描述下问题三文档哪里不符吗？

**Comment by weilaaa** [comment]
@daixh302 你好，麻烦贴一下产生第一个问题的`命令`，看起来是使用了老版本的部署脚本所致。第二、第三个问题我们会修复，感谢 bug report

**Comment by daixh302** [comment]
问题三详情截图如下：

![d476186b9d1304231abf4cdcd55e0d6](https://user-images.githubusercontent.com/22486890/129877316-a01fc3a4-3498-473c-acd2-f307da3dc0af.png)

![fbd09087d1dc17d8cc67e254170ba7f](https://user-images.githubusercontent.com/22486890/129877356-97589730-ea7f-437d-b6ed-9b6fd3c2942e.png)

**Comment by weilaaa** [comment]
问题已修复，该 issues 将关闭，如果有需要的话，欢迎随时 reopen
