### ISSUE TITLE
[Bug] When add cluster, If my kubeconfig is wrong. kubecube container will panic.

### ISSUE THREAD

**Issue by Abirdcfly** [kubecube-io/KubeCube#28]
**Describe the bug**
可以使用中文。
construct a kind cluster without sign outside ip.
when visit this kind cluster will get error `Get "https://192.168.4.124:57300/api?timeout=32s": x509: certificate is valid for 10.96.0.1, 172.18.0.3, not xxxx`
**Of course, this is a problem with my configuration, but the kubecube program should not panic**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zhujf1989** [comment]
//cc @weilaaa

**Comment by weilaaa** [comment]
@Abirdcfly Thanks for your report. Can u give the steps to reproduce the behavior and show relevant specific logs? Did you add the cluster according to the documentation?

**Comment by Abirdcfly** [comment]
```bash
kind create cluster --name kubecube-test -v=9 --config - <<EOF
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
networking:
  apiServerAddress: <ip>
EOF
```
<ip> should not be 0.0.0.0.
If setting to 0.0.0.0, kind cluster is running normally. And adding this cluster to kubecube will make kubecube  panic.
