### ISSUE TITLE
[Feature]hnc support hncresourcequota，是不是可以使用最新的来更新了？

### ISSUE THREAD

**Issue by j0rGeT** [kubecube-io/KubeCube#280]
**Is your feature request related to a problem? Please describe.**
最新的hnc 1.1版本，已经支持hncresourcequota了，是否可以后续支持hncresourcequota来控制配额了。

**Describe alternatives you've considered**
最新的hnc 1.1版本，已经支持hncresourcequota了，是否可以后续支持hncresourcequota来控制配额了。

**Comment by zhujf1989** [comment]
kubecube现有版本已经通过cubeResourcequota实现了层级配额，考虑到以下几点：
1. hnc社区并不是很活跃
2. kubecube用到hnc的能力较少，仅ns层级及权限传播
3. 每增加一个组件，运维及项目维护成本都会变高
因此，未来会去除hnc依赖，将ns层级及权限传播自研
