### ISSUE TITLE
[Feature] 文档中建议添加如何移除kubecube相关文档

### ISSUE THREAD

**Issue by 912988434** [kubecube-io/KubeCube#33]
目前使用中发现有如下问题：
1、文档中只有安装介绍，没有如何移除kubecube的介绍
2、 在已有kubernetes集群中安装的文档中，应该补充说明如何预先使用可插拔忽略某些组件的安装，比如ingress-nginx以及monintor等，避免在不知情情况下与集群中已经安装的产生冲突

**Comment by weilaaa** [comment]
感谢指出问题！

1. KubeCube 后续会提供相应的清理卸载脚本，可以让用户指定清理 kubecube、k8s、docker，或者一键清理所有的能力
2. @fusida cc

**Comment by weilaaa** [comment]
文档中已添加清理脚本
