### ISSUE TITLE
[Feature]KubeCube适配接入用户自有监控后端

### ISSUE THREAD

**Issue by JiahuiZhao11** [kubecube-io/KubeCube#35]
**Is your feature request related to a problem? Please describe.**
1. 目前用户可以修改hotplug关掉监控，但是关闭后重新登录显示401；
2. 用户无法接入自有监控后端。

**Describe the solution you'd like**
1. 修改hotplug，不允许关闭监控功能；
2. 或修改代码后添加文档，指导用户接入自有监控后端。

**Describe alternatives you've considered**

**Additional context**

**Comment by weilaaa** [comment]
目前监控为 KubeCube 默认集成的组件，在热插拔中为默认开启。用户在热插拔中主动关闭该组件，或造成对应的监控权限从原本的 aggregate 状态去除，用户访问自然会变为 401。

@JiahuiZhao11 的方案是禁用用户操作监控开关，但是赋予用户修改监控后端的能力，旨在接入已有监控的环境。有几个问题需要思考：
1. 能否在部署时就可以指定用户自有的监控后端？
2. 修改监控后端时，kubecube 原有的监控需要如何处理？
3. 原有集群中存在 metric server 时，冲突问题如何解决？

**Comment by weilaaa** [comment]
cc @zhujf1989 @fusida

**Comment by 912988434** [comment]
是否可以在安装使用的conf 文件中可以添加一个字段来判断是使用外置prometheus还是由kubecube 来安装，如果配置为外置监控，用户需要提供监控后端地址，并且可以考虑采取提供一些匹配kubecube监控页面dashboard的预定义的 servicemonitor 和rules 让用户去apply ,这样可以保证kubecube 监控页面可以正常显示，

**Comment by JiahuiZhao11** [comment]
接入自有Prometheus指导文档见：https://www.kubecube.io/docs/installation-guide/external-system-access/prometheus/
