### ISSUE TITLE
[Bug] Deployments 部署时环境变量无法输入下划线

### ISSUE THREAD

**Issue by mfuuzy** [kubecube-io/KubeCube#39]
Deployments 部署，环境变量填写的时候，输入下划线报错。系统提示是可以输入下划线的，但是输入下划线报错，应该是判断出现了问题，如下图。

![image](https://user-images.githubusercontent.com/19793458/131628443-ad1e29ff-375e-4394-afa2-71d19d67120b.png)

**Comment by wt911122** [comment]
我们已经在检查一些正则校验的问题，并将会在下版本统一修复，感谢对Kubecube的支持

**Comment by wt911122** [comment]
已解决
