### ISSUE TITLE
[Bug]集群管理添加集群成功，但是查询集群内资源报错

### ISSUE THREAD

**Issue by fei922** [kubecube-io/KubeCube#51]
**Describe the bug**
通过集群管理，成功添加了一个集群，可以查看集群信息。但是查看节点、存储类别、持久存储、网络策略均报错。查看kubecube pod 日志提示请求被管理的集群 apiserver不通

**Expected behavior**
预期既然添加集群能成功，那么也应该可以正常查看集群节点、存储类别、网络策略

**Screenshots**
![image](https://user-images.githubusercontent.com/9672023/134315902-beb1fd19-75ca-4c46-a15a-c0530a242c1d.png)
![image](https://user-images.githubusercontent.com/9672023/134313134-047daad7-566a-4e10-948d-5101f12d7495.png)
![image](https://user-images.githubusercontent.com/9672023/134313191-419362c5-6275-43a2-9e13-113b7b4a0d7f.png)

 - OS: centos 7.4
 - Version: kubecube v1.0.0

**Comment by fusida** [comment]
thank u， we have fixed #52. but now u have to use url whitout http or https.
