### ISSUE TITLE
[Feature]适应企业组织的多级租户模型的项目与空间概念问题

### ISSUE THREAD

**Issue by zhangshuiyong** [kubecube-io/KubeCube#56]
1. 从企业组织关系角度来看，常见地，项目是一个企业分配公司资源的最小粒度单元
2. 在Kubcube的组织管理中，创建租户，租户可绑定（N用户 ，N项目）

在Kubcube的资源管理中，租户分配租用了资源，下一步分配租户资源。按逻辑来，理应继承组织管理的层级，将租户资源分配给租户内的多个项目

但是，此时，就多了一个“空间”和“创建空间分配资源”的概念，让人觉得很奇怪。因为在一个企业组织中，很少有说我在一个空间中，基本上是我在哪个项目中。企业内带头人成立项目，下一步是项目审批通过了，就下发公司资源。好像很少说项目审批通过了，再创造一个空间，创建多个空间来下发公司资源。

请问在资源管理时，为什么不把租户资源直接按项目来分配？这样的企业组织逻辑不是更清晰吗？空间和创建空间的最佳实践案例是什么？

**Comment by fusida** [comment]
在部分场景下会需要项目与空间为1:n：
1、一个项目包含多个团队协作，可以使用命名空间进一步区分。
2、一个项目组件数过多，不易于管理和阅读，可以使用空间进一步区分。
3、测试和生产环境网络可达，使用同一套容器平台，一个项目拥有一个测试空间在测试环境K8s集群，拥有一个生产空间在生产环境K8s集群。

**Comment by zhangshuiyong** [comment]
get，thx @fusida

**Comment by zhujf1989** [comment]
本issue将会关闭，如有问题，可以reopen，感谢支持KubeCube！
