### ISSUE TITLE
[Feature] worker cluster shouldn't share same kubeconfig with pivot cluster

### ISSUE THREAD

**Issue by henrywangx** [kubecube-io/KubeCube#70]
Warden should only have the basic authority for updating and watch resource's change in pivot. Otherwise owner of warden cluster could operate the pivot cluster. It has a security risky of kubecube

**Comment by weilaaa** [comment]
Yes，we noticed that warden had too much authority than it need. We should lower the permissions before dispatch the kubeconfig to member cluster
