### ISSUE TITLE
[Feature] 支持网络策略的配置或者支持不同租户下的网络隔离

### ISSUE THREAD

**Issue by coolhok** [kubecube-io/KubeCube#86]
**Is your feature request related to a problem? Please describe.**

- 支持网络策略的配置
- 支持不同租户下的网络隔离

**Describe the solution you'd like**
- 租户/项目管理员可以配置网络策略
- 适配cni插件网络策略的配置

**Comment by zhujf1989** [comment]
![image](https://user-images.githubusercontent.com/13979303/150078444-4cb08330-c428-427c-8585-00795a9820ed.png)
1.0版本已经支持该功能。可以看下是否满足需求。

**Comment by zhujf1989** [comment]
@coolhok

**Comment by zhujf1989** [comment]
本issue将会关闭，如有问题，可以reopen，感谢支持KubeCube！
